default:
  image: python:3.10-slim-bullseye

stages:
  - test

test-build:
  stage: test
  script:
    - echo "Running unit tests..."
    - bash ./setup.sh
    - source venv/bin/activate
    - make test
