stages:
  - unit-test

unit-test:python3.8:
  image: python:3.8-slim-bullseye
  stage: unit-test
  script:
    - python3 -m venv/bin/activate
    - source venv/bin/activate
    - pip install --no-cache-dir -r requirements-dev.txt
    - tox -r -c tox.ini -e py38
  rules:
    - changes:
        - .vscode/**
        - .github/**
        - .gitlab/**
        - docs/**
        - resources/**
        - CHANGELOG.md
        - README.md
        - SECURITY.md
        - LICENSE
      when: never
    - when: always

unit-test:python3.9:
  image: python:3.9-slim-bullseye
  stage: unit-test
  script:
    - python3 -m venv/bin/activate
    - source venv/bin/activate
    - pip install --no-cache-dir -r requirements-dev.txt
    - tox -r -c tox.ini -e py39
  rules:
    - changes:
        - .vscode/**
        - .github/**
        - .gitlab/**
        - docs/**
        - resources/**
        - CHANGELOG.md
        - README.md
        - SECURITY.md
        - LICENSE
      when: never
    - when: always

unit-test:python3.10:
  image: python:3.10-slim-bullseye
  stage: unit-test
  script:
    - python3 -m venv/bin/activate
    - source venv/bin/activate
    - pip install --no-cache-dir -r requirements-dev.txt
    - tox -r -c tox.ini -e py310
  rules:
    - changes:
        - .vscode/**
        - .github/**
        - .gitlab/**
        - docs/**
        - resources/**
        - CHANGELOG.md
        - README.md
        - SECURITY.md
        - LICENSE
      when: never
    - when: always

unit-test:python3.11:
  image: python:3.11-slim-bullseye
  stage: unit-test
  script:
    - python3 -m venv/bin/activate
    - source venv/bin/activate
    - pip install --no-cache-dir -r requirements-dev.txt
    - tox -r -c tox.ini -e py311
  rules:
    - changes:
        - .vscode/**
        - .github/**
        - .gitlab/**
        - docs/**
        - resources/**
        - CHANGELOG.md
        - README.md
        - SECURITY.md
        - LICENSE
      when: never
    - when: always
