stages:
  - unit-test

unit-test:python3.8:
  image: python:3.8-slim-bullseye
  stage: unit-test
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -e .[dev]
    - pytest -v
  rules:
    - changes:
        - .vscode/**
        - .github/**
        - .gitlab/**
        - docs/**
        - resources/**
      when: never
    - when: always

unit-test:python3.9:
  image: python:3.9-slim-bullseye
  stage: unit-test
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -e .[dev]
    - pytest -v
  rules:
    - changes:
        - .vscode/**
        - .github/**
        - .gitlab/**
        - docs/**
        - resources/**
      when: never
    - when: always

unit-test:python3.10:
  image: python:3.10-slim-bullseye
  stage: unit-test
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -e .[dev]
    - pytest -v
  rules:
    - changes:
        - .vscode/**
        - .github/**
        - .gitlab/**
        - docs/**
        - resources/**
      when: never
    - when: always

unit-test:python3.11:
  image: python:3.11-slim-bullseye
  stage: unit-test
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -e .[dev]
    - pytest -v
  rules:
    - changes:
        - .vscode/**
        - .github/**
        - .gitlab/**
        - docs/**
        - resources/**
      when: never
    - when: always
