from octoconf.interfaces.generate_script.language_abstract_factory import ILanguageFactory
from octoconf.interfaces.generate_script.unix_script import IUnixScript
from octoconf.interfaces.generate_script.windows_script import IWindowsScript
